# Generated by Django 2.2.9 on 2022-02-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='upload',
            field=models.FileField(null=True, upload_to='static/media/'),
        ),
    ]
