# Generated by Django 2.2.9 on 2022-02-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='static/media/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
