# Generated by Django 2.2.9 on 2022-02-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20220217_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
