# Generated by Django 2.2.9 on 2022-02-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220216_1250'),
        ('chat', '0005_auto_20220217_1610'),
    ]

    operations = [
    ]
