# Generated by Django 2.2.9 on 2022-02-13 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('avtar', models.CharField(blank=True, max_length=260)),
                ('is_tutor', models.BooleanField(default=False)),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education_status', models.CharField(max_length=250, null=True)),
                ('Drive_link', models.URLField(max_length=300)),
                ('Area_of_Expertise', models.CharField(max_length=250, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('randomly_generated_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('others', 'others'), ('Programming', 'Programming'), ('Maths', 'Maths'), ('Science', 'Science')], default='others', max_length=30)),
                ('urgency', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('upload', models.FileField(null=True, upload_to='static/media/')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=500, null=True)),
                ('cost', models.CharField(max_length=50000, null=True)),
                ('day', models.CharField(max_length=250, null=True)),
                ('rating', models.IntegerField(blank=True, default=5)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Progress', 'Progress'), ('Declined', 'Declined'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Dispute', 'Dispute')], default='Open', max_length=30)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Question')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Tutor')),
            ],
        ),
    ]
