# Generated by Django 4.0 on 2021-12-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_profile_alt_email_remove_profile_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
